server:
  port: 9099
spring:
  profiles:
    active: dev
logging:
  level:
    root: INFO
    org:
      springframework: ERROR
      hibernate: ERROR
    za.co.wonderlabz: DEBUG
  pattern:
    file: '%d - %-5level %logger{36} - %msg%n'
    console: '%d - %-5level %logger{36} - %msg%n'
  file:
    name: /data/logs/yoyowallet/kyc-api.log
---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/yoyowallet?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowLoadLocalInfile=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 400
      idle-timeout: 30000
      minimum-idle: 20
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  security:
    enabled: false
  server:
    port: 9999
---
spring:
  config:
    activate:
      on-profile: uat
---
spring:
  config:
    activate:
      on-profile: prod
---
